name: Disabled Workflow
on:
  workflow_dispatch:
jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is temporarily disabled"' | base64) \
  -f sha=$(gh api /repos/{owner}/{repo}/contents/{path_to_workflow_file} | jq -r .sha)
